/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 역 목록 조회
         * @description 시드 데이터라 바뀌지 않는다 (`F-01`).
         *     `lineSeq` 오름차순 = 상행 기준 노선 순서.
         */
        get: operations["listStations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운행 조회
         * @description 구간 + 날짜로 운행을 찾는다 (`F-02`).
         *
         *     - **결과가 없으면 `200` + 빈 배열이다.** `404` 가 아니다.
         *     - `availableSeats` 는 **Redis 캐시 근사값**이며 판정 근거가 아니다.
         */
        get: operations["searchTrips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 좌석 배치도 조회
         * @description 운행 한 건의 좌석 상태 전체 (`F-03`).
         *
         *     **응답의 `lastEventId` 가 SSE 구독 시작점이다.**
         *     좌석맵을 받고 SSE 를 붙이는 사이의 변경을 놓치지 않으려면
         *     이 값을 `Last-Event-ID` 로 넘긴다 (`api.md` §6.3).
         */
        get: operations["getSeatMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/seat-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 좌석 변경 SSE 구독 — 계약의 진실은 api.md §6 이다
         * @description 운행 1개의 좌석 변경을 실시간으로 받는다 (`F-16`).
         *
         *     ⚠️ **여기 적힌 건 엔드포인트와 미디어 타입뿐이다** (`api.md` 부록 A.5).
         *     **이벤트 3종의 페이로드 · 재개 · 하트비트 규약은 `api.md` §6 이 진실이다** —
         *     `text/event-stream` 의 프레임 구조는 OpenAPI 에 표준 표현이 없다.
         *     억지로 스키마화하면 **생성 타입이 쓸모없어진다.**
         *
         *     | 항목 | 값 |
         *     |---|---|
         *     | 인증 | **없음** — `EventSource` 가 커스텀 헤더를 못 보낸다 |
         *     | 구독 단위 | **운행 1개.** 호차 필터는 클라이언트가 한다 |
         *     | 재개 | `Last-Event-ID` → Redis Stream 재생 (`XADD MAXLEN ~ 1000`) |
         *     | 하트비트 | **15초 named event.** 클라 45초 무수신 시 재연결 |
         *     | 시작점 | `GET /trips/{tripId}/seats` 응답의 **`lastEventId`** |
         *
         *     > **개인 알림을 여기 못 싣는다.** 비인증이라 서버가 "내" 를 모른다 —
         *     > 선점 만료 같은 건 **클라 타이머 + 서버 lazy 판정**으로 대체한다.
         */
        get: operations["subscribeSeatEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 좌석 선점 — 전부 성공 또는 전부 실패
         * @description 선택한 좌석을 10분간 잡는다 (`F-04`).
         *
         *     - **부분 성공이 없다.** 한 좌석이라도 실패하면 전부 실패하고, 실패한 좌석은
         *       `409` 의 `failedSeats[]` 로 돌아온다 (`api.md` §4.7).
         *     - 동시 요청은 `trip_seat.id` 오름차순 `FOR UPDATE` 로 직렬화되고
         *       `lock_timeout` 200ms 를 넘으면 `SEAT_LOCK_TIMEOUT` 이다 (`data.md` §4 · ADR-0002).
         *     - 전이 **`TS-1`** ×N + **`SH-1`**
         *
         *     멱등키는 **선택**이다. 재시도해도 좌석 상태가 진실이라 위험이 낮다 (`api.md` §2).
         */
        post: operations["createHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds/{holdId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        /**
         * 선점 조회
         * @description `POST /holds` 와 **같은 형태**를 준다 (`F-05`).
         *
         *     ⚠️ **`expires_at` 이 지났으면 DB 가 아직 `HELD` 여도 `410` 이다** — lazy 만료 판정.
         */
        get: operations["getHold"];
        put?: never;
        post?: never;
        /**
         * 선점 해제
         * @description 좌석을 즉시 돌려놓는다 (`F-06`). 전이 **`TS-2`** ×N + **`SH-3`**
         *
         *     ⚠️ **이미 만료·해제된 선점이어도 `204` 다.** `410` 을 주지 않는다 —
         *     "없애달라" 는 요청의 목적은 이미 달성됐다. **재시도가 에러가 되면
         *     클라이언트가 불필요한 분기를 갖는다** (`api.md` §5.2).
         */
        delete: operations["releaseHold"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds/{holdId}/payment-intent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 세션 발급 — 금액을 서버가 정한다
         * @description 결제창에 넘길 값을 발급하고 **`payment` 행을 `REQUESTED` 로 만든다**
         *     (전이 **`PM-1`**).
         *
         *     ⚠️ **이 단계가 있는 이유가 금액 위변조 대조다.** `orderId` 와 `amount` 를
         *     서버가 못박아 두고, 다음 단계에서 클라이언트가 돌려준 값과 맞춰 본다.
         *     **클라이언트가 보낸 `amount` 를 그대로 믿지 않는다.**
         */
        post: operations["createPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds/{holdId}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        /**
         * 결제 결과 조회 — 새 결제가 아니다
         * @description `E-03` 결제 타임아웃 때 **결과를 조회**한다.
         *
         *     ⚠️ **메서드가 `GET` 인 게 계약의 핵심이다.**
         *     클라이언트가 이걸 `POST` 로 착각하면 **이중 결제가 난다.**
         *     화면은 "다시 결제" 버튼을 잠그고 이 호출만 `Retry-After` 주기로 돌린다.
         *
         *     | 서버 판정 | 응답 |
         *     |---|---|
         *     | 확정됨 | `200` + 예약 정보 |
         *     | 아직 모름 | `202` + `Retry-After` |
         *     | 거절됨 | `402` |
         *     | 보상 취소됨 | `410` |
         */
        get: operations["getPaymentResult"];
        put?: never;
        /**
         * 결제 승인 + 예약 확정
         * @description 토스 승인을 거쳐 예약을 확정한다 (`F-08` · `F-09`).
         *
         *     **성공하면 5개 테이블이 한 트랜잭션에서 바뀐다** —
         *     전이 **`TS-4`** + **`SH-2`** + **`RV-1`** + **`PM-2`** (`data.md` §5.6).
         *
         *     ⚠️ **`Idempotency-Key` 가 필수다.** 같은 키 · 같은 본문이면 **이전 결과를
         *     그대로 재생**하고 새 승인을 하지 않는다. 타임아웃 재시도가 이중 결제가
         *     되면 안 된다.
         *
         *     ⚠️ **선점 실패가 `409` 가 아니라 `410` 인 유일한 경로다** —
         *     좌석을 뺏긴 게 아니라 **시간이 지난 것**이다.
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 예약 목록
         * @description 회원 본인의 예약 이력 (`F-12`). 정렬 **`createdAt DESC`** 고정.
         *
         *     - **취소분도 남는다** — `F-14` 는 삭제가 아니라 `CANCELLED` 전이다.
         *     - **진행 중인 선점은 여기 없다** — 선점은 예약이 아니다.
         *     - `COMPLETED` 는 **응답 시점에 파생**된다 (`data.md` §5.5).
         */
        get: operations["listReservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservationNo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 예약번호 8자리 숫자 */
                reservationNo: components["parameters"]["ReservationNoPath"];
            };
            cookie?: never;
        };
        /**
         * 예약 상세
         * @description 경로 키가 **예약번호**다 (`F-12`). 내부 `id` 를 노출하지 않는다.
         *
         *     ⚠️ **예약번호는 조회 열쇠가 아니다.** 남의 번호를 알아도 못 본다 —
         *     **로그인이 열쇠**다. 그래서 `403` 이지 `404` 가 아니다 (`api.md` §5.4).
         */
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservationNo}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 예약번호 8자리 숫자 */
                reservationNo: components["parameters"]["ReservationNoPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 예약 취소 — DELETE 가 아니다
         * @description 전이 **`TS-5`** (`SOLD`→`AVAILABLE`) + **`RV-2`** (+`PM-4` — `F-15` 는 P1).
         *
         *     ⚠️ **`DELETE` 가 아니다.** 예약은 지워지지 않고 `CANCELLED` 로 전이한다 —
         *     **이력 보존이 요구사항**이다 (`F-14`).
         *
         *     > 이 호출이 **해당 운행을 보고 있는 모든 화면에 SSE 로 좌석 복귀를 전파**한다
         *     > (`api.md` §6, `cause: RESERVATION_CANCELLED`).
         *     > 시연에서 가장 보여주기 좋은 장면이다.
         *
         *     ⚠️ **P0 단계에서는 좌석만 돌아가고 결제는 그대로 남는다.**
         *     환불(`F-15`)은 P1 이다 — 화면은 "좌석이 반환되었습니다. 환불은 별도
         *     처리됩니다" 라고 솔직하게 적는다 (`W-10`).
         */
        post: operations["cancelReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description `F-20`. 비밀번호는 **BCrypt** 로 저장한다 (`data.md` §3).
         *
         *     > **이메일 인증 · 비밀번호 재설정은 범위 밖이다** (`CLAUDE.md` 회원).
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이메일 중복 확인 — 최종 판정이 아니다
         * @description `F-21`. **폼 편의용이다.**
         *
         *     ⚠️ **`true` 를 받았어도 가입에서 `409` 가 날 수 있다.** 확인과 가입 사이에
         *     남이 채갈 수 있고, **진짜 판정은 DB unique 제약**이다.
         *     화면은 이 응답을 **가입 버튼 활성 조건으로 쓰되 결과로 믿지 않는다.**
         */
        get: operations["checkEmailAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description `F-24`. Access 15분 + Refresh 14일.
         *
         *     ⚠️ **자격 불일치는 `INVALID_CREDENTIALS` 하나뿐이다** —
         *     "없는 이메일" 과 "비밀번호 틀림" 을 나누면 **계정 존재 여부가 샌다.**
         *
         *     ⚠️ **5회 실패면 `429` 다** (`F-36`). 영구 잠금이 아니라 **5분 뒤 자동 해제**다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신 — 회전 + 재사용 탐지
         * @description `F-26`. **Refresh 토큰 자체가 인증**이라 `Authorization` 헤더를 쓰지 않는다.
         *
         *     **회전한다** — 이 호출이 성공하면 **보낸 Refresh 는 죽는다**
         *     (`data.md` §6.5 회전 6단계).
         *
         *     ⚠️ **폐기된 토큰이 다시 오면 탈취로 본다.** 그 회원의 Refresh 를 **전부 폐기**하고
         *     `401` 을 준다. 밖에서는 만료와 구분되지 않는다 — **탐지 사실은 로그에만** 남는다.
         *
         *     > **재사용 탐지 없는 회전은 회전의 절반만 하는 것이다.** 탈취범과 사용자가
         *     > 번갈아 회전하면 둘 다 무한히 갱신된다. **폐기된 `jti` 가 돌아오는 순간이
         *     > 유일한 탐지 기회다.**
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description `F-25`. Redis 에서 **Refresh 를 지운다** (`DEL` + `SREM`).
         *
         *     ⚠️ **Access 토큰은 최대 15분 더 산다** — 그게 무상태 JWT 의 대가다
         *     (`data.md` §6.5). 클라이언트는 저장된 토큰을 즉시 버려야 한다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description `F-22`. **토큰이 주체를 정하므로 식별자가 경로에 없다.**
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 정보 수정 — 이름 · 연락처만
         * @description `F-22`. **비밀번호 변경 · 이메일 변경은 범위 밖이다** (`CLAUDE.md` 회원).
         *
         *     > 여기서 이름을 바꿔도 **이미 만든 예약의 `passengerName` 은 안 변한다** —
         *     > 예약 시점 스냅샷이다 (`data.md` §3 `reservation`).
         */
        patch: operations["updateMe"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 역 코드 3자.
         *     ⚠️ **`enum` 이 아니다** — 지금은 4역이지만 역 추가가 계약 변경이 되면 안 된다
         *     (`data.md` §7 확장성).
         * @example SEO
         * @example DJN
         * @example DDG
         * @example BSN
         */
        StationCode: string;
        Station: {
            code: components["schemas"]["StationCode"];
            /** @example 서울 */
            name: string;
            /**
             * @description 노선 순서. **방향 판정의 근거** (`data.md` §8.3)
             * @example 1
             */
            lineSeq: number;
        };
        /**
         * @example {
         *       "stations": [
         *         {
         *           "code": "SEO",
         *           "name": "서울",
         *           "lineSeq": 1
         *         },
         *         {
         *           "code": "DJN",
         *           "name": "대전",
         *           "lineSeq": 2
         *         },
         *         {
         *           "code": "DDG",
         *           "name": "동대구",
         *           "lineSeq": 3
         *         },
         *         {
         *           "code": "BSN",
         *           "name": "부산",
         *           "lineSeq": 4
         *         }
         *       ]
         *     }
         */
        StationListResponse: {
            stations: components["schemas"]["Station"][];
        };
        /**
         * @description **프론트가 분기하는 열쇠.** `api.md` §4.2~§4.5 의 전체 목록이다.
         *
         *     ⚠️ **여기 없는 코드를 서버가 내려보내면 계약 위반이다.**
         *     새 코드가 필요하면 이 파일을 고치는 PR 이 먼저다 (`workflow.md` §3).
         * @enum {string}
         */
        ErrorCode: "SEAT_ALREADY_HELD" | "SEAT_LOCK_TIMEOUT" | "SEAT_COUNT_EXCEEDED" | "HOLD_EXPIRED" | "HOLD_NOT_OWNED" | "TRIP_NOT_FOUND" | "PAYMENT_DECLINED" | "PAYMENT_PENDING" | "PAYMENT_AMOUNT_MISMATCH" | "IDEMPOTENCY_KEY_REUSED" | "UNAUTHENTICATED" | "INVALID_CREDENTIALS" | "TOO_MANY_ATTEMPTS" | "EMAIL_ALREADY_EXISTS" | "RESERVATION_NOT_OWNED" | "RESERVATION_NOT_FOUND" | "RESERVATION_NOT_CANCELLABLE" | "RESERVATION_ALREADY_CANCELLED" | "VALIDATION_FAILED" | "INTERNAL_ERROR";
        /**
         * @description **모든 에러 응답의 기본형** (RFC 9457).
         *     `type` `title` 은 유형마다 고정, `detail` 은 발생마다 다르다.
         *     프론트는 **`code` 로 분기한다** — `type` URI 비교는 장황하다.
         */
        Problem: {
            /**
             * Format: uri
             * @description 문제 유형 URI. 유형마다 고정
             * @example https://api.jomin4.cloud/problems/seat-conflict
             */
            type: string;
            /**
             * @description 유형의 이름. 유형마다 고정
             * @example 좌석을 선점하지 못했습니다
             */
            title: string;
            /** @example 409 */
            status: number;
            /**
             * @description 이번 발생에 대한 설명. **`5xx` 에는 없다** (§4.5).
             * @example 선택한 6석 중 2석을 다른 고객이 먼저 선점했습니다.
             */
            detail?: string;
            /**
             * @description 요청 경로
             * @example /api/v1/holds
             */
            instance?: string;
            code: components["schemas"]["ErrorCode"];
            /**
             * @description 상관관계 ID (`api.md` §2). **모든 에러에 들어간다**
             * @example 7f3a9c21
             */
            requestId: string;
        };
        Trip: {
            /**
             * Format: int64
             * @example 101
             */
            tripId: number;
            /**
             * @description 열차번호. **하행 홀수 · 상행 짝수** (`data.md` §7)
             * @example 101
             */
            trainNo: string;
            /**
             * Format: date-time
             * @description **UTC ISO-8601.** 표시 변환은 클라이언트가 한다
             * @example 2026-09-20T00:00:00Z
             */
            departAt: string;
            /**
             * Format: date-time
             * @example 2026-09-20T02:40:00Z
             */
            arriveAt: string;
            /**
             * @description 파생값. 서버가 계산해 준다
             * @example 160
             */
            durationMinutes: number;
            /**
             * @description ⚠️ **Redis 캐시 근사값이다.**
             *     잔여 1석을 보고 들어가도 좌석 선택에서 밀릴 수 있다.
             *     **판정 근거로 쓰지 말 것** — 진실은 `POST /holds` 의 결과뿐이다.
             * @example 412
             */
            availableSeats: number;
            /**
             * @description **1인 운임**(원). 탄 구간 기준 (`data.md` §3 `fare`)
             * @example 59800
             */
            fare: number;
        };
        /**
         * @example {
         *       "trips": [
         *         {
         *           "tripId": 101,
         *           "trainNo": "101",
         *           "departAt": "2026-09-20T00:00:00Z",
         *           "arriveAt": "2026-09-20T02:40:00Z",
         *           "durationMinutes": 160,
         *           "availableSeats": 412,
         *           "fare": 59800
         *         }
         *       ]
         *     }
         */
        TripListResponse: {
            /** @description **결과가 없으면 빈 배열이다.** `404` 가 아니다 */
            trips: components["schemas"]["Trip"][];
        };
        /** @description 필드 단위 검증 실패 (§4.4) */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: {
                /** @example seats */
                field: string;
                /** @example 1~6석까지 선택할 수 있습니다 */
                reason: string;
            }[];
        };
        /**
         * @description `data.md` §5.1 `trip_seat` 상태. **이 셋만 순환한다.**
         *     선점 소유자 구분(내 선점 vs 남의 선점)은 여기 없다 —
         *     **좌석맵이 비인증이라 서버가 "내" 를 모른다** (`api.md` §6).
         *     클라이언트가 자기 `holdId` 로 대조한다.
         * @enum {string}
         */
        SeatStatus: "AVAILABLE" | "HELD" | "SOLD";
        Seat: {
            rowNo: number;
            colLetter: string;
            status: components["schemas"]["SeatStatus"];
            /** @description 창측 여부. `A` · `D` 가 창측 */
            windowSide: boolean;
        };
        Car: {
            carNo: number;
            seats: components["schemas"]["Seat"][];
        };
        /**
         * @example {
         *       "tripId": 101,
         *       "snapshotAt": "2026-09-04T05:12:33Z",
         *       "lastEventId": "1725426753000-7",
         *       "cars": [
         *         {
         *           "carNo": 4,
         *           "seats": [
         *             {
         *               "rowNo": 7,
         *               "colLetter": "A",
         *               "status": "AVAILABLE",
         *               "windowSide": true
         *             },
         *             {
         *               "rowNo": 7,
         *               "colLetter": "B",
         *               "status": "HELD",
         *               "windowSide": false
         *             }
         *           ]
         *         }
         *       ]
         *     }
         */
        SeatMapResponse: {
            /** Format: int64 */
            tripId: number;
            /**
             * Format: date-time
             * @description 이 좌석맵이 어느 시점인지
             */
            snapshotAt: string;
            /**
             * @description **SSE 구독 시작점.** Redis Stream 엔트리 ID (`밀리초-시퀀스`).
             *     이 값을 `Last-Event-ID` 로 넘기면 **좌석맵과 SSE 사이에 구멍이 없다**
             *     (`api.md` §6.3).
             * @example 1725426753000-7
             */
            lastEventId: string;
            cars: components["schemas"]["Car"][];
        };
        /**
         * @description 좌석 주소 **호차-행-열** (`data.md` §1). 예 `4호차 7A`
         * @example {
         *       "carNo": 4,
         *       "rowNo": 7,
         *       "colLetter": "A"
         *     }
         */
        SeatAddress: {
            carNo: number;
            rowNo: number;
            colLetter: string;
        };
        /**
         * @example {
         *       "tripId": 101,
         *       "seats": [
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "A"
         *         },
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "B"
         *         }
         *       ]
         *     }
         */
        HoldRequest: {
            /**
             * Format: int64
             * @example 101
             */
            tripId: number;
            /**
             * @description ⚠️ **전부 성공하거나 전부 실패한다** (`F-04` · ADR-0002).
             *     한 좌석이라도 잡히면 나머지도 잡히지 않는다 — 부분 성공은 없다.
             */
            seats: components["schemas"]["SeatAddress"][];
        };
        /**
         * @description 선점 식별자 = **`seat_hold.public_id`** (`data.md` §3).
         *     `h_` + hex 6자리 · `char(8)`.
         *
         *     ⚠️ **내부 `seat_hold.id` 가 아니다.** `reservation_no` 와 같은 판단이다 —
         *     내부 `bigserial` 을 URL 에 노출하지 않는다 (`api.md` §3).
         *     **불투명 문자열로 다룰 것** — 파싱하거나 증감시키지 말 것.
         * @example h_8f3a21
         */
        HoldId: string;
        /**
         * @description `POST /holds` 와 `GET /holds/{holdId}` 가 **같은 형태**를 준다
         * @example {
         *       "holdId": "h_8f3a21",
         *       "tripId": 101,
         *       "seats": [
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "A"
         *         },
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "B"
         *         }
         *       ],
         *       "expiresAt": "2026-09-04T05:22:33Z",
         *       "remainingSeconds": 600,
         *       "totalFare": 119600
         *     }
         */
        HoldResponse: {
            holdId: components["schemas"]["HoldId"];
            /** Format: int64 */
            tripId: number;
            seats: components["schemas"]["SeatAddress"][];
            /**
             * Format: date-time
             * @description 선점 만료 시각 (생성 + 10분).
             *     ⚠️ **타이머는 이 값에서 역산한다.** 인터벌 카운트로 만들면
             *     **모바일 백그라운드에서 멈춘다** (`E-04`).
             */
            expiresAt: string;
            /**
             * @description 남은 초. **시계 오차를 잡는 보조값**이지 타이머의 근거가 아니다.
             * @example 600
             */
            remainingSeconds: number;
            /**
             * @description 선택한 좌석 수 × 1인 운임 (원)
             * @example 119600
             */
            totalFare: number;
        };
        /**
         * @description **`ALL_OR_NOTHING` 이 이 프로젝트의 계약을 드러내는 값이다.**
         *     "이 좌석 자체는 멀쩡한데 **같이 고른 좌석 때문에 함께 실패했다**" 는 뜻이다.
         *     `E-01` 의 "함께 선택한 7A도 선점되지 않았습니다" 문구가 여기서 나온다.
         * @enum {string}
         */
        SeatFailureReason: "HELD_BY_OTHER" | "ALL_OR_NOTHING";
        FailedSeat: components["schemas"]["SeatAddress"] & {
            reason: components["schemas"]["SeatFailureReason"];
        };
        /**
         * @description `409` 두 가지를 **하나의 스키마로** 준다. **`code` 로 분기한다** (`api.md` §4.2).
         *
         *     | `code` | 뜻 | 화면 |
         *     |---|---|---|
         *     | `SEAT_ALREADY_HELD` | 남이 먼저 가졌다 | **다른 좌석을 고르게** |
         *     | `SEAT_LOCK_TIMEOUT` | 락 대기 200ms 초과 | **다시 시도** |
         *
         *     ⚠️ **`failedSeats` 는 `SEAT_ALREADY_HELD` 에만 있다.**
         *     락 타임아웃은 **어느 좌석이 문제인지 서버도 모른다** — 잠그지 못했으니까.
         */
        SeatConflictProblem: components["schemas"]["Problem"] & {
            failedSeats?: components["schemas"]["FailedSeat"][];
        };
        /**
         * @description 결제 주문 식별자 = **`payment.order_id`** (`data.md` §3).
         *     `ord_` + hex 8자리.
         *
         *     ⚠️ **서버가 발급한다.** 클라이언트는 받은 값을 그대로 되돌려줄 뿐이다 —
         *     이 값으로 서버가 `payment` 행을 찾아 **금액을 대조**한다.
         * @example ord_9c2f4a17
         */
        OrderId: string;
        /**
         * @description 결제창에 넘길 값. **금액을 서버가 정한다** (전이 `PM-1`).
         *
         *     > 클라이언트가 보낸 `amount` 를 그대로 믿으면 안 된다.
         *     > 그래서 이 단계에서 `payment` 행을 `REQUESTED` 로 미리 만든다.
         * @example {
         *       "orderId": "ord_9c2f4a17",
         *       "amount": 119600,
         *       "orderName": "KTX 101 · 4호차 7A 외 1석"
         *     }
         */
        PaymentIntentResponse: {
            orderId: components["schemas"]["OrderId"];
            /**
             * @description **서버가 정한 금액.** 다음 단계에서 이 값과 대조한다
             * @example 119600
             */
            amount: number;
            /**
             * @description 토스 결제창에 표시될 문구
             * @example KTX 101 · 4호차 7A 외 1석
             */
            orderName: string;
        };
        /**
         * @description 예약번호 **8자리 숫자 무작위** (`data.md` §3 `reservation_no`).
         *
         *     ⚠️ **식별용이지 조회 열쇠가 아니다.** 이 번호를 알아도 남의 예약은 못 본다 —
         *     조회는 로그인으로만 된다 (`403 RESERVATION_NOT_OWNED`).
         * @example 48207315
         */
        ReservationNo: string;
        /**
         * @description ⚠️ **`COMPLETED` 는 DB 에 없다** (`data.md` §5.5).
         *     `depart_at < now()` 로 **응답 시점에 파생**한다.
         *     **클라이언트는 파생인지 저장인지 알 필요가 없다** — 서버가 준 대로 표시한다.
         * @enum {string}
         */
        ReservationStatus: "CONFIRMED" | "CANCELLED" | "COMPLETED";
        /**
         * @description 예약이 자기 구간을 스스로 설명하기 위한 최소 정보
         * @example {
         *       "code": "SEO",
         *       "name": "서울"
         *     }
         */
        StationBrief: {
            code: string;
            name: string;
        };
        /**
         * @description **값 스냅샷**이다 (`data.md` §3 `reservation_seat`).
         *     `trip_seat` 을 가리키지 않는다 — 취소하면 그 좌석은 남에게 팔리는데,
         *     참조로 두면 **취소된 예약이 남의 좌석을 가리키게 된다.**
         */
        ReservedSeat: {
            carNo: number;
            rowNo: number;
            colLetter: string;
            /**
             * @description **예약 시점 운임.** 나중에 운임이 바뀌어도 이 값은 안 변한다
             * @example 59800
             */
            fare: number;
        };
        /**
         * @description 예약 상세. **네 곳이 같은 형태를 준다** —
         *     결제 확정(`201`) · 결제 결과 조회(`200`) · 예약 상세(`200`) · 취소(`200`).
         *
         *     > **자기 구간과 예매자를 스스로 설명한다.** `W-10` 은 목록을 거치지 않고
         *     > `/reservations/48207315` 로 바로 열릴 수 있다. 그때 운행 정보를
         *     > 따로 조회해야 한다면 화면이 두 번 깜빡인다.
         * @example {
         *       "reservationNo": "48207315",
         *       "status": "CONFIRMED",
         *       "tripId": 101,
         *       "trainNo": "KTX 101",
         *       "fromStation": {
         *         "code": "SEO",
         *         "name": "서울"
         *       },
         *       "toStation": {
         *         "code": "BSN",
         *         "name": "부산"
         *       },
         *       "departAt": "2026-09-10T21:00:00Z",
         *       "arriveAt": "2026-09-10T23:17:00Z",
         *       "passengerName": "홍길동",
         *       "passengerPhone": "010-0000-0000",
         *       "seats": [
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "A",
         *           "fare": 59800
         *         },
         *         {
         *           "carNo": 4,
         *           "rowNo": 7,
         *           "colLetter": "B",
         *           "fare": 59800
         *         }
         *       ],
         *       "totalFare": 119600,
         *       "paidAt": "2026-09-04T05:18:02Z"
         *     }
         */
        Reservation: {
            reservationNo: components["schemas"]["ReservationNo"];
            status: components["schemas"]["ReservationStatus"];
            /**
             * Format: int64
             * @example 101
             */
            tripId: number;
            /** @example KTX 101 */
            trainNo: string;
            fromStation: components["schemas"]["StationBrief"];
            toStation: components["schemas"]["StationBrief"];
            /**
             * Format: date-time
             * @description **UTC ISO-8601**
             */
            departAt: string;
            /** Format: date-time */
            arriveAt: string;
            /**
             * @description **예약 시점 스냅샷** (`data.md` §3).
             *     회원 정보에서 자동으로 채워지고, 나중에 회원이 이름을 바꿔도 **이 값은 안 변한다**.
             * @example 홍길동
             */
            passengerName: string;
            /** @example 010-0000-0000 */
            passengerPhone: string;
            seats: components["schemas"]["ReservedSeat"][];
            /** @example 119600 */
            totalFare: number;
            /**
             * Format: date-time
             * @description 결제 승인 시각
             */
            paidAt?: string;
            /**
             * Format: date-time
             * @description `status` 가 `CANCELLED` 일 때만 있다
             */
            cancelledAt?: string;
        };
        /**
         * @description **`202` 는 에러가 아니다.** 그런데 `Problem` 형태로 준다 —
         *     성공 응답과 형태가 달라야 클라이언트가 분기를 틀리지 않는다 (`api.md` §4.3).
         *
         *     **200 도 5xx 도 아닌 세 번째 상태다.** 승인이 됐는지 서버도 아직 모른다
         *     (`data.md` §5.3 — `payment` 가 `REQUESTED` 에 머물러 있다).
         */
        PaymentPendingProblem: components["schemas"]["Problem"];
        /**
         * @description 토스 결제창이 돌려준 값을 그대로 서버에 넘긴다.
         *
         *     ⚠️ **`amount` 를 보내지만 서버는 이걸 믿지 않는다.**
         *     `orderId` 로 찾은 `payment.amount` 와 **대조**하고, 다르면
         *     `400 PAYMENT_AMOUNT_MISMATCH` 다. 보내는 이유는 대조 대상이 필요해서다.
         */
        PaymentConfirmRequest: {
            /**
             * @description 토스페이먼츠 `paymentKey`
             * @example tviva20260904103254KDMbN
             */
            paymentKey: string;
            orderId: components["schemas"]["OrderId"];
            /** @example 119600 */
            amount: number;
        };
        /**
         * @description **`PageResponse<T>` 의 메타 부분** (`api.md` §0).
         *
         *     ⚠️ **Spring Data 의 `Page` 를 그대로 노출하지 않는다.** `:adapter-web` 에
         *     자체 타입을 정의한다 — 프레임워크 타입이 계약에 새면 §3 규칙이 처음부터 깨진다.
         *
         *     OpenAPI 에 제네릭이 없어서 **목록마다 `content` 를 붙인 스키마를 따로 만든다**
         *     (예: `ReservationPage`).
         */
        PageMeta: {
            /**
             * @description 0-based
             * @example 0
             */
            page: number;
            /** @example 20 */
            size: number;
            /** @example 43 */
            totalElements: number;
            /** @example 3 */
            totalPages: number;
        };
        /**
         * @description `W-09` 목록 한 줄 — **예약번호 · 열차 · 일시 · 좌석 · 상태**.
         *
         *     > **취소된 예약도 목록에 남는다.** `F-14` 는 삭제가 아니라 `CANCELLED` 전이다.
         *     > **진행 중인 선점은 여기 없다** — 선점은 예약이 아니다.
         */
        ReservationSummary: {
            reservationNo: components["schemas"]["ReservationNo"];
            status: components["schemas"]["ReservationStatus"];
            /** @example KTX 101 */
            trainNo: string;
            /** Format: date-time */
            departAt: string;
            seats: components["schemas"]["ReservedSeat"][];
            /** @example 119600 */
            totalFare: number;
        };
        /**
         * @description `PageResponse<ReservationSummary>` (`api.md` §0).
         *     정렬은 **`createdAt DESC`** 고정 — 정렬 파라미터를 열지 않는다.
         */
        ReservationPage: components["schemas"]["PageMeta"] & {
            content: components["schemas"]["ReservationSummary"][];
        };
        /**
         * Format: email
         * @example hong@example.com
         */
        Email: string;
        /**
         * Format: password
         * @description ⚠️ **최대 72바이트.** BCrypt 가 72바이트를 넘는 입력을 **조용히 자른다** —
         *     길이를 안 막으면 "73번째 글자부터는 아무거나 통과" 가 된다 (`data.md` §3 `password_hash`).
         */
        Password: string;
        /** @example 010-0000-0000 */
        PhoneNumber: string;
        SignupRequest: {
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
            /** @example 홍길동 */
            name: string;
            phone: components["schemas"]["PhoneNumber"];
        };
        /**
         * @description **내부 `member.id` 를 노출하지 않는다** (`api.md` §3).
         *     `/me` 는 토큰이 주체를 정하므로 식별자가 경로에 필요 없다.
         * @example {
         *       "email": "hong@example.com",
         *       "name": "홍길동",
         *       "phone": "010-0000-0000",
         *       "createdAt": "2026-08-01T09:00:00Z"
         *     }
         */
        MemberProfile: {
            email: components["schemas"]["Email"];
            /** @example 홍길동 */
            name: string;
            phone: components["schemas"]["PhoneNumber"];
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @description ⚠️ **최종 판정이 아니다.** 확인과 가입 사이에 남이 채갈 수 있다.
         *     **진짜 판정은 가입 요청의 DB unique 제약**이고, 이건 폼 편의용이다 (`F-21`).
         * @example {
         *       "available": true
         *     }
         */
        EmailAvailability: {
            available: boolean;
        };
        LoginRequest: {
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
        };
        /**
         * @description **Refresh 는 회전한다** (`data.md` §6.5). 이 응답을 받으면 **이전 Refresh 는 죽는다** —
         *     들고 있다가 다시 쓰면 **재사용 탐지**에 걸려 그 회원의 토큰이 전부 폐기된다.
         * @example {
         *       "accessToken": "eyJhbGc…",
         *       "refreshToken": "eyJhbGc…",
         *       "accessExpiresAt": "2026-09-04T05:27:33Z"
         *     }
         */
        TokenPair: {
            /** @description Access JWT · **15분** */
            accessToken: string;
            /** @description Refresh JWT · **14일** · Redis 저장 · 회전 */
            refreshToken: string;
            /**
             * Format: date-time
             * @description Access 만료 시각. **선제 갱신의 근거**다 —
             *     `401` 을 받고 나서 갱신하면 사용자 동작 하나가 실패한 뒤다.
             */
            accessExpiresAt: string;
        };
        /**
         * @description **Refresh 토큰 자체가 인증이다** — `Authorization` 헤더를 쓰지 않는다.
         *     Access 가 이미 만료된 상태에서 부르는 호출이라 그럴 수밖에 없다.
         */
        RefreshRequest: {
            refreshToken: string;
        };
        /**
         * @description **이름 · 연락처만 (`F-22`).**
         *     비밀번호 변경 · 이메일 변경 · 이메일 인증은 **범위 밖**이다 (`CLAUDE.md` 회원).
         */
        UpdateProfileRequest: {
            name?: string;
            phone?: components["schemas"]["PhoneNumber"];
        };
    };
    responses: {
        /**
         * @description `5xx` — **`detail` 이 없다.** 스택 트레이스 · SQL · 내부 경로가 새면 안 된다 (§4.5).
         *     `requestId` 만 준다.
         */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "일시적인 오류가 발생했습니다",
                 *       "status": 500,
                 *       "code": "INTERNAL_ERROR",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `400` — 요청이 올바르지 않다 */
        ValidationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/validation",
                 *       "title": "요청이 올바르지 않습니다",
                 *       "status": 400,
                 *       "code": "VALIDATION_FAILED",
                 *       "requestId": "7f3a9c21",
                 *       "errors": [
                 *         {
                 *           "field": "to",
                 *           "reason": "출발역과 도착역이 같습니다"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description `404` — 운행이 없다 */
        TripNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/not-found",
                 *       "title": "운행을 찾을 수 없습니다",
                 *       "status": 404,
                 *       "code": "TRIP_NOT_FOUND",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `201` — 선점 성공. 전이 `TS-1` ×N + `SH-1` */
        HoldCreated: {
            headers: {
                /**
                 * @description 생성된 선점의 위치
                 * @example /api/v1/holds/h_8f3a21
                 */
                Location?: string;
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HoldResponse"];
            };
        };
        /**
         * @description `400` — **두 가지 `code` 가 온다.**
         *
         *     | `code` | 언제 |
         *     |---|---|
         *     | `SEAT_COUNT_EXCEEDED` | 0석이거나 6석 초과. **버튼 비활성으로 미리 막는다** |
         *     | `VALIDATION_FAILED` | 그 밖의 형식 오류. `errors[]` 가 붙는다 |
         */
        BadHoldRequest: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/seat-count",
                 *       "title": "좌석 수가 올바르지 않습니다",
                 *       "status": 400,
                 *       "detail": "한 번에 1~6석까지 선택할 수 있습니다.",
                 *       "code": "SEAT_COUNT_EXCEEDED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"] | components["schemas"]["ValidationProblem"];
            };
        };
        /**
         * @description `401` — 토큰이 없거나 만료됐다.
         *     ⚠️ **화면은 로그인으로 보낸 뒤 원래 자리로 복원해야 한다** — 좌석 선택 중이었을 수 있다.
         */
        Unauthenticated: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/unauthenticated",
                 *       "title": "로그인이 필요합니다",
                 *       "status": 401,
                 *       "code": "UNAUTHENTICATED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `409` — 선점 실패. **경합은 정상 결과다** — 서버는 이걸 `ERROR` 로 로깅하지 않는다
         *     (`operate.md` §1).
         */
        SeatConflict: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["SeatConflictProblem"];
            };
        };
        /**
         * @description `403` — 남의 선점이다.
         *     ⚠️ **`404` 가 아니다** — 존재는 하되 권한이 없다는 뜻을 그대로 준다 (`F-31`).
         */
        HoldNotOwned: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/hold-not-owned",
                 *       "title": "접근할 수 없는 선점입니다",
                 *       "status": 403,
                 *       "code": "HOLD_NOT_OWNED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `410` — 선점이 만료됐다.
         *
         *     ⚠️ **DB 가 아직 `HELD` 여도 `410` 을 준다** (`data.md` §5.2 lazy 판정).
         *     만료 회수 스케줄러가 30초 주기라 최대 30초의 창이 생기는데, **이 판정이 그 창을 메운다.**
         *
         *     화면은 **좌석 선택으로 되돌린다** (`E-02`). 만료된 선점을 되살리지 않는다.
         */
        HoldExpired: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/hold-expired",
                 *       "title": "선점 시간이 만료되었습니다",
                 *       "status": 410,
                 *       "detail": "좌석을 다시 선택해 주세요.",
                 *       "code": "HOLD_EXPIRED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `200` — 결제 세션 발급. 전이 **`PM-1`** */
        PaymentIntentCreated: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PaymentIntentResponse"];
            };
        };
        /**
         * @description `202` — **결과 미확정.** `PM-1` 유지.
         *
         *     ⚠️ **클라이언트는 `GET /holds/{holdId}/payment` 로 폴링한다** (`E-03`).
         *     **다시 `POST` 하면 이중 결제다** — 화면에서 "다시 결제" 버튼을 잠근다.
         */
        PaymentPending: {
            headers: {
                /**
                 * @description 초. 이 시간 뒤에 `GET` 으로 조회한다
                 * @example 2
                 */
                "Retry-After"?: number;
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/payment-pending",
                 *       "title": "결제 결과를 확인하는 중입니다",
                 *       "status": 202,
                 *       "detail": "잠시 후 결제 결과를 조회해 주세요.",
                 *       "code": "PAYMENT_PENDING",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["PaymentPendingProblem"];
            };
        };
        /**
         * @description `402` — 승인 거절. 전이 **`PM-3`**
         *
         *     ⚠️ **선점은 유지된다.** 다른 수단으로 재시도할 수 있다 —
         *     좌석을 놓치게 만들 이유가 없다.
         */
        PaymentDeclined: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/payment-declined",
                 *       "title": "결제가 거절되었습니다",
                 *       "status": 402,
                 *       "detail": "다른 결제 수단으로 다시 시도해 주세요.",
                 *       "code": "PAYMENT_DECLINED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `201` — **예약 확정.** 전이 **`TS-4`** + **`SH-2`** + **`RV-1`** + **`PM-2`**
         *
         *     ⚠️ **이 시스템에서 가장 무거운 호출이다** — 5개 테이블이 한 트랜잭션에서 바뀐다
         *     (`data.md` §5.6).
         */
        ReservationConfirmed: {
            headers: {
                /**
                 * @description 생성된 예약의 위치
                 * @example /api/v1/reservations/48207315
                 */
                Location?: string;
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Reservation"];
            };
        };
        /**
         * @description `400` — **두 가지 `code` 가 온다.**
         *
         *     | `code` | 언제 |
         *     |---|---|
         *     | `PAYMENT_AMOUNT_MISMATCH` | `payment-intent` 가 못박은 금액과 다르다 |
         *     | `VALIDATION_FAILED` | 형식 오류. `errors[]` 가 붙는다 |
         */
        BadPaymentRequest: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/payment-amount-mismatch",
                 *       "title": "결제 금액이 일치하지 않습니다",
                 *       "status": 400,
                 *       "code": "PAYMENT_AMOUNT_MISMATCH",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"] | components["schemas"]["ValidationProblem"];
            };
        };
        /**
         * @description `409` — **같은 `Idempotency-Key` 에 다른 본문**이 왔다.
         *
         *     | 상황 | 결과 |
         *     |---|---|
         *     | 같은 키 · **같은 본문** | ✅ **이전 결과를 그대로 재생.** 새 승인을 안 한다 |
         *     | 같은 키 · **다른 본문** | ❌ 이 응답 |
         *
         *     ⚠️ 이 에러가 나면 **클라이언트가 키를 잘못 쓰고 있다** —
         *     버튼을 누를 때마다 새로 만들었거나, 재시도에 다른 키를 붙였다 (`api.md` §2).
         */
        IdempotencyKeyReused: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/idempotency-key-reused",
                 *       "title": "중복된 결제 요청입니다",
                 *       "status": 409,
                 *       "code": "IDEMPOTENCY_KEY_REUSED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `200` — 예약 상세 */
        ReservationDetail: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Reservation"];
            };
        };
        /**
         * @description `403` — 남의 예약이다.
         *
         *     > **`404` 로 숨기지 않는다** (`api.md` §5.4).
         *     > 예약번호가 조회 열쇠가 아니라 **로그인이 열쇠**이므로,
         *     > 이미 인증된 사용자에게 존재 여부를 숨겨서 얻는 게 적다.
         */
        ReservationNotOwned: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/reservation-not-owned",
                 *       "title": "접근할 수 없는 예약입니다",
                 *       "status": 403,
                 *       "code": "RESERVATION_NOT_OWNED",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `404` — 그런 예약번호가 없다 */
        ReservationNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/reservation-not-found",
                 *       "title": "예약을 찾을 수 없습니다",
                 *       "status": 404,
                 *       "code": "RESERVATION_NOT_FOUND",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `409` — 취소할 수 없다. **두 가지 `code` 가 온다.**
         *
         *     | `code` | 언제 | 화면 |
         *     |---|---|---|
         *     | `RESERVATION_NOT_CANCELLABLE` | **출발 시각이 지났다** | 취소 버튼 비활성 + 사유 표기 |
         *     | `RESERVATION_ALREADY_CANCELLED` | 이미 취소됨 | 목록을 새로 고친다 |
         */
        ReservationNotCancellable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `201` — 가입 완료 */
        MemberCreated: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MemberProfile"];
            };
        };
        /**
         * @description `409` — 이미 쓰는 이메일이다.
         *
         *     > `GET /auth/email-available` 이 `true` 를 줬어도 여기서 `409` 가 날 수 있다.
         *     > **그 사이에 남이 채간 것**이고, 그게 정상이다.
         */
        EmailAlreadyExists: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/email-exists",
                 *       "title": "이미 가입된 이메일입니다",
                 *       "status": 409,
                 *       "code": "EMAIL_ALREADY_EXISTS",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `401` — **자격 불일치.**
         *
         *     ⚠️ **"없는 이메일" 과 "비밀번호 틀림" 을 구분하지 않는다.**
         *     나누는 순간 **계정 존재 여부가 새어나간다.** 화면 문구도 하나여야 한다.
         *
         *     **`POST /auth/refresh` 의 실패도 같은 코드다** — 만료된 토큰이든
         *     **재사용 탐지**든 밖에서는 구분되지 않는다 (`data.md` §6.5).
         *     탐지 사실은 **로그에만 남는다** (`WARN` · `event=REFRESH_REUSE_DETECTED`).
         */
        InvalidCredentials: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/invalid-credentials",
                 *       "title": "이메일 또는 비밀번호가 올바르지 않습니다",
                 *       "status": 401,
                 *       "code": "INVALID_CREDENTIALS",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `429` — 로그인 시도 제한 (`F-36`).
         *
         *     ⚠️ **영구 잠금이 아니다.** `Retry-After` 가 화면 문구의 근거다 —
         *     **"계정이 잠겼습니다" 가 아니라 "5분 뒤 다시 시도하세요"** 여야 한다.
         *     비밀번호 재설정이 범위 밖이라 **영구 잠금이면 계정이 그대로 죽는다.**
         *
         *     > 키가 `email` 인 이유도 존재 여부 은닉이다 (`data.md` §6.6).
         *     > 없는 이메일도 똑같이 카운트돼야 **차단 여부로 계정 존재를 역추적할 수 없다.**
         */
        TooManyAttempts: {
            headers: {
                /**
                 * @description 초. **300 고정** — 차단이 풀리기까지
                 * @example 300
                 */
                "Retry-After"?: number;
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.jomin4.cloud/problems/too-many-attempts",
                 *       "title": "로그인 시도가 너무 많습니다",
                 *       "status": 429,
                 *       "detail": "5분 뒤 다시 시도해 주세요.",
                 *       "code": "TOO_MANY_ATTEMPTS",
                 *       "requestId": "7f3a9c21"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description 출발역 코드
         * @example SEO
         */
        From: components["schemas"]["StationCode"];
        /**
         * @description 도착역 코드. **`from` 과 같으면 `400`**
         * @example BSN
         */
        To: components["schemas"]["StationCode"];
        /**
         * @description **KST 영업일** (`YYYY-MM-DD`).
         *     ⚠️ 시각이 아니다 — 응답의 `departAt` 은 UTC 순간이지만 이건 날짜다 (`api.md` §0).
         * @example 2026-09-20
         */
        Date: string;
        /** @description 인원. 좌석 6석 상한과 같은 근거 (`F-04`) */
        Passengers: number;
        /**
         * @description 운행 ID
         * @example 101
         */
        TripId: number;
        /**
         * @description 호차. **없으면 800석 전체를 준다**
         * @example 4
         */
        CarNo: number;
        /**
         * @description ⚠️ **화면 진입 시 1회 생성하고 재시도에도 같은 값을 쓴다.**
         *     버튼을 누를 때마다 새로 만들면 멱등성이 무의미하다.
         *     **모바일은 영속 저장해야 한다** — 앱이 죽으면 메모리 키가 사라진다 (`api.md` §2).
         */
        IdempotencyKey: string;
        /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
        XRequestIdHeader: string;
        /** @description 선점 식별자 (불투명 문자열) */
        HoldIdPath: components["schemas"]["HoldId"];
        /** @description 0-based 페이지 번호 */
        Page: number;
        /** @description 페이지 크기 */
        Size: number;
        /** @description 예약번호 8자리 숫자 */
        ReservationNoPath: components["schemas"]["ReservationNo"];
    };
    requestBodies: never;
    headers: {
        /**
         * @description 상관관계 ID (`api.md` §2). 요청의 `X-Request-Id` 를 에코하거나 서버가 생성한다.
         *     **모든 응답에 붙는다** — 아래 에러 응답 컴포넌트에만 적은 건
         *     OpenAPI 에 "전역 응답 헤더" 표현이 없어서다.
         * @example 7f3a9c21
         */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 역 목록 */
            200: {
                headers: {
                    /** @description 하루 캐시 */
                    "Cache-Control"?: "public, max-age=86400";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    searchTrips: {
        parameters: {
            query: {
                /**
                 * @description 출발역 코드
                 * @example SEO
                 */
                from: components["parameters"]["From"];
                /**
                 * @description 도착역 코드. **`from` 과 같으면 `400`**
                 * @example BSN
                 */
                to: components["parameters"]["To"];
                /**
                 * @description **KST 영업일** (`YYYY-MM-DD`).
                 *     ⚠️ 시각이 아니다 — 응답의 `departAt` 은 UTC 순간이지만 이건 날짜다 (`api.md` §0).
                 * @example 2026-09-20
                 */
                date: components["parameters"]["Date"];
                /** @description 인원. 좌석 6석 상한과 같은 근거 (`F-04`) */
                passengers?: components["parameters"]["Passengers"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 운행 목록 (없으면 빈 배열) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripListResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getSeatMap: {
        parameters: {
            query?: {
                /**
                 * @description 호차. **없으면 800석 전체를 준다**
                 * @example 4
                 */
                carNo?: components["parameters"]["CarNo"];
            };
            header?: never;
            path: {
                /**
                 * @description 운행 ID
                 * @example 101
                 */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 좌석맵 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatMapResponse"];
                };
            };
            404: components["responses"]["TripNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    subscribeSeatEvents: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 마지막으로 받은 이벤트 ID. 재연결 시 SSE 표준 헤더로 자동 전송된다.
                 *     **보관 범위를 벗어나면 `resume-failed` 이벤트**가 내려온다 —
                 *     HTTP 에러가 아니다 (`api.md` §6.3).
                 */
                "Last-Event-ID"?: string;
            };
            path: {
                /**
                 * @description 운행 ID
                 * @example 101
                 */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 이벤트 스트림. **끊기지 않는다** — 정상 종료는 클라이언트가 닫을 때뿐이다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["TripNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createHold: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description ⚠️ **화면 진입 시 1회 생성하고 재시도에도 같은 값을 쓴다.**
                 *     버튼을 누를 때마다 새로 만들면 멱등성이 무의미하다.
                 *     **모바일은 영속 저장해야 한다** — 앱이 죽으면 메모리 키가 사라진다 (`api.md` §2).
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            201: components["responses"]["HoldCreated"];
            400: components["responses"]["BadHoldRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["TripNotFound"];
            409: components["responses"]["SeatConflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 선점 정보 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["HoldNotOwned"];
            410: components["responses"]["HoldExpired"];
            500: components["responses"]["InternalError"];
        };
    };
    releaseHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `204` — 해제됨. **멱등하다** */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["HoldNotOwned"];
            500: components["responses"]["InternalError"];
        };
    };
    createPaymentIntent: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaymentIntentCreated"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["HoldNotOwned"];
            410: components["responses"]["HoldExpired"];
            500: components["responses"]["InternalError"];
        };
    };
    getPaymentResult: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `200` — 확정됨. `POST` 의 `201` 과 같은 본문 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            202: components["responses"]["PaymentPending"];
            401: components["responses"]["Unauthenticated"];
            402: components["responses"]["PaymentDeclined"];
            403: components["responses"]["HoldNotOwned"];
            410: components["responses"]["HoldExpired"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description ⚠️ **필수.** 화면 진입 시 1회 생성하고 재시도에도 같은 값을 쓴다.
                 *     **모바일은 영속 저장해야 한다** — 앱이 죽으면 메모리 키가 사라지고
                 *     그게 곧 이중 결제다 (`E-04`).
                 */
                "Idempotency-Key": string;
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path: {
                /** @description 선점 식별자 (불투명 문자열) */
                holdId: components["parameters"]["HoldIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequest"];
            };
        };
        responses: {
            201: components["responses"]["ReservationConfirmed"];
            202: components["responses"]["PaymentPending"];
            400: components["responses"]["BadPaymentRequest"];
            401: components["responses"]["Unauthenticated"];
            402: components["responses"]["PaymentDeclined"];
            403: components["responses"]["HoldNotOwned"];
            409: components["responses"]["IdempotencyKeyReused"];
            410: components["responses"]["HoldExpired"];
            500: components["responses"]["InternalError"];
        };
    };
    listReservations: {
        parameters: {
            query?: {
                /** @description 0-based 페이지 번호 */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 */
                size?: components["parameters"]["Size"];
            };
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 예약 목록 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path: {
                /** @description 예약번호 8자리 숫자 */
                reservationNo: components["parameters"]["ReservationNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ReservationDetail"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ReservationNotOwned"];
            404: components["responses"]["ReservationNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelReservation: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path: {
                /** @description 예약번호 8자리 숫자 */
                reservationNo: components["parameters"]["ReservationNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `200` — 취소됨. **갱신된 예약**을 준다 (`status: CANCELLED`) */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ReservationNotOwned"];
            404: components["responses"]["ReservationNotFound"];
            409: components["responses"]["ReservationNotCancellable"];
            500: components["responses"]["InternalError"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            201: components["responses"]["MemberCreated"];
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["EmailAlreadyExists"];
            500: components["responses"]["InternalError"];
        };
    };
    checkEmailAvailable: {
        parameters: {
            query: {
                email: components["schemas"]["Email"];
            };
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용 가능 여부 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailAvailability"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 토큰 쌍 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["InvalidCredentials"];
            429: components["responses"]["TooManyAttempts"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description **새** 토큰 쌍. 이전 Refresh 는 이 시점에 죽는다 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["InvalidCredentials"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `204` — 로그아웃됨 */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 정보 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfile"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description 없으면 서버가 생성한다. **응답에 그대로 에코된다** */
                "X-Request-Id"?: components["parameters"]["XRequestIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 갱신된 회원 정보 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfile"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
}
